version: '3'
services:
  node-app:
    container_name: node-app
    build: .
    image: maverick4060/short_url_code:short_url_with_redis
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    container_name: redis-server
    ports:
      - "6379:6379"
